---
- name: Installer toutes les dépendances nécessaires
  hosts: localhost
  become: yes

  roles:
    - docker         # Appelle le rôle pour installer Docker
    - minikube     # Appelle le rôle pour installer Kubernetes
    - helm           # Appelle le rôle pour installer Helm
    #- swap_disable   # Appelle le rôle pour désactiver le swap
