---
- name: Kubernetes Port Forwarding for WebGoat
  hosts: localhost
  tasks:
      - name: Forward port 8080 from WebGoat service to local machine
        command: "kubectl port-forward -n k8s-ns-development svc/webgoat-service-development 8080:8080"
        async: 0
        poll: 0
        background: yes
        register: port_forward
        ignore_errors: true

      - name: Wait for port forwarding to start
        pause:
            minutes: 1

      - name: Ensure the port forwarding is still running
        shell: "pgrep -f 'kubectl port-forward' || echo 'port-forward not running'"
        register: pf_status
        retries: 5
        delay: 10
        until: pf_status.stdout != 'port-forward not running'

      - name: Notify user about port forwarding
        debug:
            msg: "Port forwarding is running, access WebGoat at http://localhost:8080/WebGoat/login"

      - name: Ensure WebGoat service is accessible
        command: curl http://localhost:8080/WebGoat/login
        register: result
        ignore_errors: yes

      - name: Display curl response
        debug:
            msg: "Curl request output: {{ result.stdout }}"

      - name: Check curl response status
        debug:
            msg: "Curl request failed with status: {{ result.rc }}"
        when: result.rc != 0
