apiVersion: v1
kind: Service
metadata:
  name: projetfinal-service
spec:
  type: NodePort  # or LoadBalancer if in the cloud
  selector:
    app: projetfinal
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080    # Must match containerPort
      nodePort: 30007     # Port on the node for local access

