name: Publish Docker image

on:
    # workflow_run:
    #   workflows: [CodeQL]
    #   types:
    #     - completed
    push:
        branches:
            - feature/ansible-setup

jobs:
    push_to_registry:
        name: Push Docker image to Docker Hub
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write
        steps:
            - name: Check out the repo
              uses: actions/checkout@v2

            - name: Log in to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                  images: log8100projet/projetfinal

            - name: Build and push Docker image
              id: push
              uses: docker/build-push-action@v3
              with:
                  context: .
                  file: ./Dockerfile
                  push: true
                  tags: |
                      log8100projet/projetfinal:latest
                      ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
            - name: Install Dependencies
              run: |
                  curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
                  sudo install minikube-linux-amd64 /usr/local/bin/minikube

            - name: Start Minikube with Nodes
              run: |
                  chmod +x ./terraform/setup_minikube.sh
                  ./terraform/setup_minikube.sh

            - name: Run Ansible Playbook for Initial Configuration
              run: |
                  ansible-playbook ./playbooks/setup-cluster.yml
                  ansible-playbook ./playbooks/deploy-app.yml

            - name: Run Terraform Apply
              working-directory: ./terraform
              run: |
                  terraform init
                  terraform apply -auto-approve
